System.config({
  "defaultJSExtensions": true,
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime"
    ],
    "stage": 1
  },
  "typescriptOptions": {
    "emitDecoratorMetadata": true
  },
  "paths": {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  "bundles": {
    "build/main": [
      "npm:base64-js@0.0.8/lib/b64.js",
      "npm:ieee754@1.1.5/index.js",
      "npm:is-array@1.0.1/index.js",
      "npm:process@0.10.1/browser.js",
      "npm:inherits@2.0.1/inherits_browser.js",
      "npm:create-hash@1.1.1/helpers.js",
      "npm:ripemd160@1.0.1/lib/ripemd160.js",
      "npm:sha.js@2.4.2/hash.js",
      "npm:sha.js@2.4.2/sha1.js",
      "npm:sha.js@2.4.2/sha256.js",
      "npm:sha.js@2.4.2/sha512.js",
      "npm:events@1.0.2/events.js",
      "npm:isarray@0.0.1/index.js",
      "npm:core-util-is@1.0.1/lib/util.js",
      "npm:readable-stream@1.1.13/lib/_stream_writable.js",
      "npm:string_decoder@0.10.31/index.js",
      "npm:readable-stream@1.1.13/lib/_stream_transform.js",
      "npm:readable-stream@1.1.13/lib/_stream_passthrough.js",
      "npm:readable-stream@1.1.13/writable.js",
      "npm:readable-stream@1.1.13/duplex.js",
      "npm:readable-stream@1.1.13/transform.js",
      "npm:readable-stream@1.1.13/passthrough.js",
      "npm:create-hmac@1.1.3/browser.js",
      "npm:browserify-sign@3.0.2/algos.js",
      "npm:pbkdf2@3.0.4/browser.js",
      "npm:browserify-aes@1.0.1/aes.js",
      "npm:browserify-aes@1.0.1/cipherBase.js",
      "npm:browserify-aes@1.0.1/modes.js",
      "npm:browserify-aes@1.0.1/EVP_BytesToKey.js",
      "npm:browserify-aes@1.0.1/streamCipher.js",
      "npm:browserify-aes@1.0.1/ghash.js",
      "npm:browserify-aes@1.0.1/xor.js",
      "npm:browserify-aes@1.0.1/modes/ecb.js",
      "npm:browserify-aes@1.0.1/modes/cbc.js",
      "npm:browserify-aes@1.0.1/modes/cfb.js",
      "npm:browserify-aes@1.0.1/modes/cfb8.js",
      "npm:browserify-aes@1.0.1/modes/cfb1.js",
      "npm:browserify-aes@1.0.1/modes/ofb.js",
      "npm:browserify-aes@1.0.1/modes/ctr.js",
      "npm:browserify-aes@1.0.1/decrypter.js",
      "npm:bn.js@2.0.5/lib/bn.js",
      "npm:brorand@1.0.5/index.js",
      "npm:diffie-hellman@3.0.2/lib/primes.json!github:systemjs/plugin-json@0.1.0.js",
      "npm:diffie-hellman@3.0.2/lib/dh.js",
      "npm:indexof@0.0.1/index.js",
      "npm:asn1.js@2.0.3/lib/asn1/base/reporter.js",
      "npm:asn1.js@2.0.3/lib/asn1/base/buffer.js",
      "npm:minimalistic-assert@1.0.0/index.js",
      "npm:asn1.js@2.0.3/lib/asn1/constants/der.js",
      "npm:asn1.js@2.0.3/lib/asn1/decoders/der.js",
      "npm:asn1.js@2.0.3/lib/asn1/encoders/der.js",
      "npm:parse-asn1@3.0.1/aesid.json!github:systemjs/plugin-json@0.1.0.js",
      "npm:parse-asn1@3.0.1/EVP_BytesToKey.js",
      "npm:elliptic@3.0.4/package.json!github:systemjs/plugin-json@0.1.0.js",
      "npm:elliptic@3.0.4/lib/elliptic/utils.js",
      "npm:hash.js@1.0.3/lib/hash/utils.js",
      "npm:hash.js@1.0.3/lib/hash/common.js",
      "npm:hash.js@1.0.3/lib/hash/sha.js",
      "npm:hash.js@1.0.3/lib/hash/ripemd.js",
      "npm:hash.js@1.0.3/lib/hash/hmac.js",
      "npm:elliptic@3.0.4/lib/elliptic/curve/base.js",
      "npm:elliptic@3.0.4/lib/elliptic/curve/short.js",
      "npm:elliptic@3.0.4/lib/elliptic/curve/mont.js",
      "npm:elliptic@3.0.4/lib/elliptic/curve/edwards.js",
      "npm:elliptic@3.0.4/lib/elliptic/precomputed/secp256k1.js",
      "npm:elliptic@3.0.4/lib/elliptic/ec/key.js",
      "npm:elliptic@3.0.4/lib/elliptic/ec/signature.js",
      "npm:browserify-rsa@2.0.1/index.js",
      "npm:browserify-sign@3.0.2/curves.js",
      "npm:browserify-sign@3.0.2/verify.js",
      "npm:create-ecdh@2.0.1/browser.js",
      "npm:public-encrypt@2.0.1/mgf.js",
      "npm:public-encrypt@2.0.1/xor.js",
      "npm:public-encrypt@2.0.1/withPublic.js",
      "npm:public-encrypt@2.0.1/privateDecrypt.js",
      "npm:core-js@0.9.14/modules/$.fw.js",
      "npm:core-js@0.9.14/modules/$.dom-create.js",
      "npm:core-js@0.9.14/modules/$.shared.js",
      "npm:core-js@0.9.14/modules/$.uid.js",
      "npm:core-js@0.9.14/modules/$.redef.js",
      "npm:core-js@0.9.14/modules/$.invoke.js",
      "npm:core-js@0.9.14/modules/$.assert.js",
      "npm:core-js@0.9.14/modules/$.array-includes.js",
      "npm:core-js@0.9.14/modules/$.replacer.js",
      "npm:core-js@0.9.14/modules/$.throws.js",
      "npm:core-js@0.9.14/modules/$.keyof.js",
      "npm:core-js@0.9.14/modules/$.enum-keys.js",
      "npm:core-js@0.9.14/modules/$.get-names.js",
      "npm:core-js@0.9.14/modules/$.assign.js",
      "npm:core-js@0.9.14/modules/$.same.js",
      "npm:core-js@0.9.14/modules/$.set-proto.js",
      "npm:core-js@0.9.14/modules/es6.object.to-string.js",
      "npm:core-js@0.9.14/modules/es6.object.statics-accept-primitives.js",
      "npm:core-js@0.9.14/modules/es6.function.name.js",
      "npm:core-js@0.9.14/modules/es6.function.has-instance.js",
      "npm:core-js@0.9.14/modules/es6.number.constructor.js",
      "npm:core-js@0.9.14/modules/es6.number.statics.js",
      "npm:core-js@0.9.14/modules/es6.math.js",
      "npm:core-js@0.9.14/modules/es6.string.from-code-point.js",
      "npm:core-js@0.9.14/modules/es6.string.raw.js",
      "npm:core-js@0.9.14/modules/$.string-at.js",
      "npm:core-js@0.9.14/modules/$.iter.js",
      "npm:core-js@0.9.14/modules/$.iter-define.js",
      "npm:core-js@0.9.14/modules/es6.string.code-point-at.js",
      "npm:core-js@0.9.14/modules/es6.string.ends-with.js",
      "npm:core-js@0.9.14/modules/es6.string.includes.js",
      "npm:core-js@0.9.14/modules/$.string-repeat.js",
      "npm:core-js@0.9.14/modules/es6.string.starts-with.js",
      "npm:core-js@0.9.14/modules/$.iter-call.js",
      "npm:core-js@0.9.14/modules/$.iter-detect.js",
      "npm:core-js@0.9.14/modules/es6.array.of.js",
      "npm:core-js@0.9.14/modules/$.unscope.js",
      "npm:core-js@0.9.14/modules/$.species.js",
      "npm:core-js@0.9.14/modules/es6.array.copy-within.js",
      "npm:core-js@0.9.14/modules/es6.array.fill.js",
      "npm:core-js@0.9.14/modules/es6.array.find.js",
      "npm:core-js@0.9.14/modules/es6.array.find-index.js",
      "npm:core-js@0.9.14/modules/es6.regexp.js",
      "npm:core-js@0.9.14/modules/$.for-of.js",
      "npm:core-js@0.9.14/modules/$.task.js",
      "npm:core-js@0.9.14/modules/$.mix.js",
      "npm:core-js@0.9.14/modules/$.collection-strong.js",
      "npm:core-js@0.9.14/modules/$.collection.js",
      "npm:core-js@0.9.14/modules/es6.set.js",
      "npm:core-js@0.9.14/modules/$.collection-weak.js",
      "npm:core-js@0.9.14/modules/es6.weak-set.js",
      "npm:core-js@0.9.14/modules/$.own-keys.js",
      "npm:core-js@0.9.14/modules/es7.array.includes.js",
      "npm:core-js@0.9.14/modules/es7.string.at.js",
      "npm:core-js@0.9.14/modules/$.string-pad.js",
      "npm:core-js@0.9.14/modules/es7.string.rpad.js",
      "npm:core-js@0.9.14/modules/es7.regexp.escape.js",
      "npm:core-js@0.9.14/modules/es7.object.get-own-property-descriptors.js",
      "npm:core-js@0.9.14/modules/es7.object.to-array.js",
      "npm:core-js@0.9.14/modules/$.collection-to-json.js",
      "npm:core-js@0.9.14/modules/es7.set.to-json.js",
      "npm:core-js@0.9.14/modules/js.array.statics.js",
      "npm:core-js@0.9.14/modules/$.partial.js",
      "npm:core-js@0.9.14/modules/web.immediate.js",
      "npm:core-js@0.9.14/modules/web.dom.iterable.js",
      "npm:core-js@0.9.14/library/modules/$.fw.js",
      "npm:core-js@0.9.14/library/modules/$.shared.js",
      "npm:core-js@0.9.14/library/modules/$.uid.js",
      "npm:core-js@0.9.14/library/modules/$.def.js",
      "npm:core-js@0.9.14/library/modules/$.redef.js",
      "npm:core-js@0.9.14/library/modules/$.keyof.js",
      "npm:core-js@0.9.14/library/modules/$.enum-keys.js",
      "npm:core-js@0.9.14/library/modules/$.assert.js",
      "npm:core-js@0.9.14/library/modules/$.get-names.js",
      "npm:core-js@0.9.14/library/modules/$.string-at.js",
      "npm:core-js@0.9.14/library/modules/$.iter.js",
      "npm:core-js@0.9.14/library/modules/$.iter-define.js",
      "npm:core-js@0.9.14/library/modules/$.unscope.js",
      "npm:core-js@0.9.14/library/fn/object/create.js",
      "npm:core-js@0.9.14/library/modules/es6.object.to-string.js",
      "npm:core-js@0.9.14/library/modules/$.ctx.js",
      "npm:core-js@0.9.14/library/modules/$.iter-call.js",
      "npm:core-js@0.9.14/library/modules/$.set-proto.js",
      "npm:core-js@0.9.14/library/modules/$.same.js",
      "npm:core-js@0.9.14/library/modules/$.species.js",
      "npm:core-js@0.9.14/library/modules/$.invoke.js",
      "npm:core-js@0.9.14/library/modules/$.dom-create.js",
      "npm:core-js@0.9.14/library/modules/$.mix.js",
      "npm:core-js@0.9.14/library/modules/$.iter-detect.js",
      "npm:core-js@0.9.14/library/fn/object/define-property.js",
      "npm:babel-runtime@5.5.4/helpers/class-call-check.js",
      "npm:babel-runtime@5.5.4/helpers/inherits.js",
      "npm:core-js@0.9.14/library/modules/es6.object.statics-accept-primitives.js",
      "npm:core-js@0.9.14/library/modules/es6.number.statics.js",
      "npm:core-js@0.9.14/library/fn/object/keys.js",
      "npm:core-js@0.9.14/library/modules/core.iter-helpers.js",
      "npm:core-js@0.9.14/library/fn/get-iterator.js",
      "npm:angular2@2.0.0-alpha.26/src/di/annotations_impl.js",
      "npm:angular2@2.0.0-alpha.26/src/util/decorators.js",
      "npm:angular2@2.0.0-alpha.26/src/reflection/types.js",
      "npm:angular2@2.0.0-alpha.26/src/reflection/reflection_capabilities.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/parser/locals.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/exceptions.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/interfaces.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/constants.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/pipes/pipe.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/change_detector_ref.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/proto_record.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/directive_record.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/coalesce.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/binding_record.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/pipes/pipe_registry.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/pipes/null_pipe.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/change_detection_jit_generator.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/pregen_proto_change_detector.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/pipes/iterable_changes.js",
      "npm:core-js@0.9.14/library/modules/$.collection-strong.js",
      "npm:core-js@0.9.14/library/modules/$.collection.js",
      "npm:core-js@0.9.14/library/modules/$.collection-to-json.js",
      "npm:rx@2.5.1/dist/rx.js",
      "npm:rx@2.5.1/dist/rx.aggregates.js",
      "npm:rx@2.5.1/dist/rx.async.js",
      "npm:rx@2.5.1/dist/rx.backpressure.js",
      "npm:rx@2.5.1/dist/rx.binding.js",
      "npm:rx@2.5.1/dist/rx.coincidence.js",
      "npm:rx@2.5.1/dist/rx.experimental.js",
      "npm:rx@2.5.1/dist/rx.joinpatterns.js",
      "npm:rx@2.5.1/dist/rx.sorting.js",
      "npm:rx@2.5.1/dist/rx.virtualtime.js",
      "npm:rx@2.5.1/dist/rx.testing.js",
      "npm:rx@2.5.1/dist/rx.time.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/pipes/promise_pipe.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/pipes/uppercase_pipe.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/pipes/lowercase_pipe.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/pipes/json_pipe.js",
      "npm:angular2@2.0.0-alpha.26/src/di/forward_ref.js",
      "npm:angular2@2.0.0-alpha.26/src/di/type_literal.js",
      "npm:angular2@2.0.0-alpha.26/src/di/exceptions.js",
      "npm:angular2@2.0.0-alpha.26/src/di/opaque_token.js",
      "npm:angular2@2.0.0-alpha.26/src/core/annotations_impl/visibility.js",
      "npm:angular2@2.0.0-alpha.26/src/core/annotations_impl/view.js",
      "npm:angular2@2.0.0-alpha.26/src/dom/dom_adapter.js",
      "npm:angular2@2.0.0-alpha.26/src/dom/generic_browser_adapter.js",
      "npm:angular2@2.0.0-alpha.26/src/core/annotations_impl/annotations.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/view_ref.js",
      "npm:angular2@2.0.0-alpha.26/src/core/annotations_impl/di.js",
      "npm:angular2@2.0.0-alpha.26/src/render/api.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/element_binder.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/view_pool.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/view_listener.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/view_container_ref.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/view/view.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/directive_lifecycle_reflector.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/base_query_list.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/template_resolver.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/component_url_mapper.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/proto_view_factory.js",
      "npm:angular2@2.0.0-alpha.26/src/services/url_resolver.js",
      "npm:angular2@2.0.0-alpha.26/src/core/exception_handler.js",
      "npm:angular2@2.0.0-alpha.26/src/render/xhr.js",
      "npm:angular2@2.0.0-alpha.26/src/core/zone/ng_zone.js",
      "npm:angular2@2.0.0-alpha.26/src/core/life_cycle/life_cycle.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/shadow_dom/shadow_dom_strategy.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/shadow_dom/light_dom.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/shadow_dom/shadow_css.js",
      "npm:angular2@2.0.0-alpha.26/src/render/xhr_impl.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/events/event_manager.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/events/key_events.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/events/hammer_common.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/shadow_dom/style_url_resolver.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/shadow_dom/style_inliner.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/dynamic_component_loader.js",
      "npm:angular2@2.0.0-alpha.26/src/core/testability/get_testability.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/shadow_dom/content_tag.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/util.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/view/element.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/view/view_container.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/compiler/compile_element.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/compiler/compile_control.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/view/element_binder.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/compiler/property_binding_parser.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/compiler/text_interpolation_parser.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/compiler/selector.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/compiler/view_splitter.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/shadow_dom/shadow_dom_compile_step.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/view/property_setter_factory.js",
      "npm:angular2@2.0.0-alpha.26/src/core/application_tokens.js",
      "npm:angular2@2.0.0-alpha.26/src/core/annotations/di.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/interfaces.js",
      "npm:angular2@2.0.0-alpha.26/src/core/annotations/annotations.js",
      "npm:angular2@2.0.0-alpha.26/src/core/annotations/decorators.js",
      "npm:angular2@2.0.0-alpha.26/src/directives/ng_for.js",
      "npm:angular2@2.0.0-alpha.26/src/directives/ng_if.js",
      "npm:angular2@2.0.0-alpha.26/src/directives/ng_non_bindable.js",
      "npm:angular2@2.0.0-alpha.26/src/directives/ng_switch.js",
      "npm:angular2@2.0.0-alpha.26/src/directives/class.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/validators.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/directives/control_container.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/directives/ng_control.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/directives/shared.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/directives/ng_form_control.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/directives/ng_model.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/directives/ng_control_group.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/directives/ng_form_model.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/directives/ng_form.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/directives/default_value_accessor.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/directives/checkbox_value_accessor.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/directives/select_control_value_accessor.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/directives/validators.js",
      "app/services/Foo.js",
      "npm:base64-js@0.0.8.js",
      "npm:ieee754@1.1.5.js",
      "npm:is-array@1.0.1.js",
      "npm:process@0.10.1.js",
      "npm:inherits@2.0.1.js",
      "npm:create-hash@1.1.1/md5.js",
      "npm:ripemd160@1.0.1.js",
      "npm:sha.js@2.4.2/sha.js",
      "npm:sha.js@2.4.2/sha224.js",
      "npm:sha.js@2.4.2/sha384.js",
      "npm:events@1.0.2.js",
      "npm:isarray@0.0.1.js",
      "npm:core-util-is@1.0.1.js",
      "npm:readable-stream@1.1.13/lib/_stream_duplex.js",
      "npm:string_decoder@0.10.31.js",
      "npm:create-hmac@1.1.3.js",
      "npm:pbkdf2@3.0.4.js",
      "npm:browserify-aes@1.0.1/authCipher.js",
      "npm:bn.js@2.0.5.js",
      "npm:brorand@1.0.5.js",
      "npm:indexof@0.0.1.js",
      "npm:minimalistic-assert@1.0.0.js",
      "npm:asn1.js@2.0.3/lib/asn1/constants/index.js",
      "npm:asn1.js@2.0.3/lib/asn1/decoders/index.js",
      "npm:asn1.js@2.0.3/lib/asn1/encoders/index.js",
      "npm:parse-asn1@3.0.1/fixProc.js",
      "npm:hash.js@1.0.3/lib/hash.js",
      "npm:elliptic@3.0.4/lib/elliptic/curve/index.js",
      "npm:elliptic@3.0.4/lib/elliptic/curves.js",
      "npm:elliptic@3.0.4/lib/elliptic/ec/index.js",
      "npm:browserify-rsa@2.0.1.js",
      "npm:create-ecdh@2.0.1/index.js",
      "npm:public-encrypt@2.0.1/publicEncrypt.js",
      "npm:core-js@0.9.14/modules/$.js",
      "npm:core-js@0.9.14/modules/$.wks.js",
      "npm:core-js@0.9.14/modules/$.def.js",
      "npm:core-js@0.9.14/modules/$.ctx.js",
      "npm:core-js@0.9.14/modules/es6.symbol.js",
      "npm:core-js@0.9.14/modules/es6.object.assign.js",
      "npm:core-js@0.9.14/modules/es6.object.is.js",
      "npm:core-js@0.9.14/modules/es6.object.set-prototype-of.js",
      "npm:core-js@0.9.14/modules/es6.string.iterator.js",
      "npm:core-js@0.9.14/modules/es6.string.repeat.js",
      "npm:core-js@0.9.14/modules/es6.array.from.js",
      "npm:core-js@0.9.14/modules/es6.array.iterator.js",
      "npm:core-js@0.9.14/modules/es6.array.species.js",
      "npm:core-js@0.9.14/modules/es6.promise.js",
      "npm:core-js@0.9.14/modules/es6.map.js",
      "npm:core-js@0.9.14/modules/es6.weak-map.js",
      "npm:core-js@0.9.14/modules/es6.reflect.js",
      "npm:core-js@0.9.14/modules/es7.string.lpad.js",
      "npm:core-js@0.9.14/modules/es7.map.to-json.js",
      "npm:core-js@0.9.14/modules/web.timers.js",
      "npm:core-js@0.9.14/library/modules/$.js",
      "npm:core-js@0.9.14/library/modules/$.wks.js",
      "npm:core-js@0.9.14/library/modules/es6.string.iterator.js",
      "npm:core-js@0.9.14/library/modules/es6.array.iterator.js",
      "npm:babel-runtime@5.5.4/core-js/object/create.js",
      "npm:core-js@0.9.14/library/modules/$.for-of.js",
      "npm:core-js@0.9.14/library/modules/$.task.js",
      "npm:babel-runtime@5.5.4/core-js/object/define-property.js",
      "npm:core-js@0.9.14/library/fn/object/get-own-property-descriptor.js",
      "npm:core-js@0.9.14/library/fn/number/is-integer.js",
      "npm:babel-runtime@5.5.4/core-js/object/keys.js",
      "npm:core-js@0.9.14/library/fn/is-iterable.js",
      "npm:babel-runtime@5.5.4/core-js/get-iterator.js",
      "npm:angular2@2.0.0-alpha.26/src/di/annotations.js",
      "npm:angular2@2.0.0-alpha.26/src/reflection/reflector.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/change_detection_util.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/abstract_change_detector.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/jit_proto_change_detector.js",
      "npm:core-js@0.9.14/library/modules/es6.map.js",
      "npm:core-js@0.9.14/library/modules/es7.map.to-json.js",
      "npm:rx@2.5.1/index.js",
      "npm:angular2@2.0.0-alpha.26/src/di/key.js",
      "npm:angular2@2.0.0-alpha.26/src/core/annotations/visibility.js",
      "npm:angular2@2.0.0-alpha.26/src/core/annotations/view.js",
      "npm:angular2@2.0.0-alpha.26/src/dom/browser_adapter.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/directive_resolver.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/view.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/element_ref.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/query_list.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/compiler/template_loader.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/shadow_dom/util.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/events/hammer_gestures.js",
      "npm:angular2@2.0.0-alpha.26/src/core/testability/testability.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/view/proto_view.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/view/proto_view_builder.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/compiler/directive_parser.js",
      "npm:angular2@2.0.0-alpha.26/annotations.js",
      "npm:angular2@2.0.0-alpha.26/directives.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/model.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/directives/ng_control_name.js",
      "app/components/SeedApp.js",
      "npm:buffer@3.2.2/index.js",
      "github:jspm/nodelibs-process@0.1.1/index.js",
      "npm:sha.js@2.4.2/index.js",
      "github:jspm/nodelibs-events@0.1.1/index.js",
      "npm:readable-stream@1.1.13/lib/_stream_readable.js",
      "npm:browserify-aes@1.0.1/encrypter.js",
      "npm:miller-rabin@2.0.1/lib/mr.js",
      "npm:vm-browserify@0.0.4/index.js",
      "npm:asn1.js@2.0.3/lib/asn1/base/node.js",
      "npm:hash.js@1.0.3.js",
      "npm:create-ecdh@2.0.1.js",
      "npm:public-encrypt@2.0.1/browser.js",
      "npm:core-js@0.9.14/modules/$.cof.js",
      "npm:core-js@0.9.14/modules/$.array-methods.js",
      "npm:core-js@0.9.14/library/modules/$.cof.js",
      "npm:core-js@0.9.14/library/modules/web.dom.iterable.js",
      "npm:core-js@0.9.14/library/modules/es6.promise.js",
      "npm:babel-runtime@5.5.4/helpers/create-class.js",
      "npm:babel-runtime@5.5.4/core-js/object/get-own-property-descriptor.js",
      "npm:babel-runtime@5.5.4/core-js/number/is-integer.js",
      "npm:babel-runtime@5.5.4/core-js/is-iterable.js",
      "npm:angular2@2.0.0-alpha.26/src/di/decorators.js",
      "npm:angular2@2.0.0-alpha.26/src/reflection/reflection.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/dynamic_change_detector.js",
      "npm:core-js@0.9.14/library/fn/map.js",
      "npm:rx@2.5.1.js",
      "npm:angular2@2.0.0-alpha.26/src/di/binding.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/view_manager_utils.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/shadow_dom/emulated_unscoped_shadow_dom_strategy.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/dom_renderer.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/compiler/compile_pipeline.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/compiler/compile_step_factory.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/form_builder.js",
      "npm:angular2@2.0.0-alpha.26/src/forms/directives.js",
      "npm:buffer@3.2.2.js",
      "github:jspm/nodelibs-process@0.1.1.js",
      "npm:sha.js@2.4.2.js",
      "github:jspm/nodelibs-events@0.1.1.js",
      "npm:readable-stream@1.1.13/readable.js",
      "npm:browserify-aes@1.0.1/browser.js",
      "npm:miller-rabin@2.0.1.js",
      "npm:vm-browserify@0.0.4.js",
      "npm:asn1.js@2.0.3/lib/asn1/base/index.js",
      "npm:elliptic@3.0.4/lib/elliptic/hmac-drbg.js",
      "npm:public-encrypt@2.0.1.js",
      "npm:core-js@0.9.14/modules/es5.js",
      "npm:core-js@0.9.14/library/modules/es6.symbol.js",
      "npm:core-js@0.9.14/library/fn/symbol/iterator.js",
      "npm:core-js@0.9.14/library/fn/promise.js",
      "npm:babel-runtime@5.5.4/helpers/get.js",
      "npm:angular2@2.0.0-alpha.26/src/facade/lang.js",
      "npm:angular2@2.0.0-alpha.26/src/facade/collection.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/parser/lexer.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/parser/parser.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/proto_change_detector.js",
      "npm:babel-runtime@5.5.4/core-js/map.js",
      "npm:angular2@2.0.0-alpha.26/src/facade/async.js",
      "npm:angular2@2.0.0-alpha.26/src/di/injector.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/view_manager.js",
      "npm:angular2@2.0.0-alpha.26/src/render/dom/compiler/compiler.js",
      "npm:angular2@2.0.0-alpha.26/forms.js",
      "github:jspm/nodelibs-buffer@0.1.0/index.js",
      "npm:stream-browserify@1.0.0/index.js",
      "npm:browserify-aes@1.0.1.js",
      "npm:diffie-hellman@3.0.2/lib/generatePrime.js",
      "github:jspm/nodelibs-vm@0.1.0/index.js",
      "npm:elliptic@3.0.4/lib/elliptic.js",
      "npm:core-js@0.9.14/shim.js",
      "npm:core-js@0.9.14/library/fn/symbol/index.js",
      "npm:babel-runtime@5.5.4/core-js/symbol/iterator.js",
      "npm:babel-runtime@5.5.4/core-js/promise.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/parser/ast.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/pipes/keyvalue_changes.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/pipes/observable_pipe.js",
      "npm:angular2@2.0.0-alpha.26/di.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/element_injector.js",
      "github:jspm/nodelibs-buffer@0.1.0.js",
      "npm:stream-browserify@1.0.0.js",
      "npm:diffie-hellman@3.0.2/browser.js",
      "github:jspm/nodelibs-vm@0.1.0.js",
      "npm:elliptic@3.0.4.js",
      "npm:core-js@0.9.14/library/fn/symbol.js",
      "npm:angular2@2.0.0-alpha.26/src/change_detection/change_detection.js",
      "npm:angular2@2.0.0-alpha.26/src/core/compiler/compiler.js",
      "npm:randombytes@2.0.1/browser.js",
      "github:jspm/nodelibs-stream@0.1.0/index.js",
      "npm:diffie-hellman@3.0.2.js",
      "npm:asn1.js@2.0.3/lib/asn1/api.js",
      "npm:babel-runtime@5.5.4/core-js/symbol.js",
      "npm:angular2@2.0.0-alpha.26/change_detection.js",
      "npm:angular2@2.0.0-alpha.26/src/core/application.js",
      "npm:randombytes@2.0.1.js",
      "github:jspm/nodelibs-stream@0.1.0.js",
      "npm:asn1.js@2.0.3/lib/asn1.js",
      "npm:babel-runtime@5.5.4/regenerator/runtime.js",
      "npm:angular2@2.0.0-alpha.26/core.js",
      "npm:create-hash@1.1.1/browser.js",
      "npm:asn1.js@2.0.3.js",
      "npm:babel-core@5.5.6/lib/babel/polyfill.js",
      "npm:angular2@2.0.0-alpha.26/angular2.js",
      "npm:create-hash@1.1.1.js",
      "npm:parse-asn1@3.0.1/asn1.js",
      "npm:babel-core@5.5.6/polyfill.js",
      "npm:parse-asn1@3.0.1/index.js",
      "npm:parse-asn1@3.0.1.js",
      "npm:browserify-sign@3.0.2/sign.js",
      "npm:browserify-sign@3.0.2/browser.js",
      "npm:browserify-sign@3.0.2.js",
      "npm:crypto-browserify@3.9.14/index.js",
      "npm:crypto-browserify@3.9.14.js",
      "github:jspm/nodelibs-crypto@0.1.0/index.js",
      "github:jspm/nodelibs-crypto@0.1.0.js",
      "npm:reflect-metadata@0.1.0/Reflect.js",
      "npm:reflect-metadata@0.1.0.js",
      "app/main.js"
    ]
  }
});

System.config({
  "map": {
    "angular2": "npm:angular2@2.0.0-alpha.26",
    "babel": "npm:babel-core@5.5.6",
    "babel-runtime": "npm:babel-runtime@5.5.4",
    "core-js": "npm:core-js@0.9.14",
    "es6-shim": "github:es-shims/es6-shim@0.31.3",
    "polymer/polymer": "github:polymer/polymer@1.0.3",
    "reflect-metadata": "npm:reflect-metadata@0.1.0",
    "traceur": "github:jmcriffey/bower-traceur@0.0.90",
    "traceur-runtime": "github:jmcriffey/bower-traceur-runtime@0.0.90",
    "typescript": "github:mhegazy/typescript@v1.5-beta2",
    "zone.js": "npm:zone.js@0.5.1",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.2.2"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.9.14"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.1": {
      "process": "npm:process@0.10.1"
    },
    "github:jspm/nodelibs-querystring@0.1.0": {
      "querystring": "npm:querystring@0.2.0"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:amdefine@0.1.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "module": "github:jspm/nodelibs-module@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:angular2@2.0.0-alpha.26": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "reflect-metadata": "npm:reflect-metadata@0.1.0",
      "rtts_assert": "npm:rtts_assert@2.0.0-alpha.26",
      "rx": "npm:rx@2.5.1",
      "traceur": "npm:traceur@0.0.87",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "zone.js": "npm:zone.js@0.5.0"
    },
    "npm:asn1.js@2.0.4": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "bn.js": "npm:bn.js@2.0.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.5.4": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:brace-expansion@1.1.0": {
      "balanced-match": "npm:balanced-match@0.2.0",
      "concat-map": "npm:concat-map@0.0.1"
    },
    "npm:browserify-aes@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:browserify-rsa@2.0.1": {
      "bn.js": "npm:bn.js@2.0.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.1"
    },
    "npm:browserify-sign@3.0.2": {
      "bn.js": "npm:bn.js@2.0.5",
      "browserify-rsa": "npm:browserify-rsa@2.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.1",
      "create-hmac": "npm:create-hmac@1.1.3",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@3.1.0",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@3.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:buffer@3.2.2": {
      "base64-js": "npm:base64-js@0.0.8",
      "ieee754": "npm:ieee754@1.1.6",
      "is-array": "npm:is-array@1.0.1"
    },
    "npm:commander@2.6.0": {
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@0.9.14": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-util-is@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@2.0.1": {
      "bn.js": "npm:bn.js@2.0.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@3.1.0"
    },
    "npm:create-hash@1.1.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:create-hmac@1.1.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.9.14": {
      "browserify-aes": "npm:browserify-aes@1.0.1",
      "browserify-sign": "npm:browserify-sign@3.0.2",
      "create-ecdh": "npm:create-ecdh@2.0.1",
      "create-hash": "npm:create-hash@1.1.1",
      "create-hmac": "npm:create-hmac@1.1.3",
      "diffie-hellman": "npm:diffie-hellman@3.0.2",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "public-encrypt": "npm:public-encrypt@2.0.1",
      "randombytes": "npm:randombytes@2.0.1"
    },
    "npm:diffie-hellman@3.0.2": {
      "bn.js": "npm:bn.js@2.0.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@2.0.1",
      "randombytes": "npm:randombytes@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:elliptic@3.1.0": {
      "bn.js": "npm:bn.js@2.0.5",
      "brorand": "npm:brorand@1.0.5",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:glob@4.3.5": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inflight": "npm:inflight@1.0.4",
      "inherits": "npm:inherits@2.0.1",
      "minimatch": "npm:minimatch@2.0.8",
      "once": "npm:once@1.3.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:inflight@1.0.4": {
      "once": "npm:once@1.3.2",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "wrappy": "npm:wrappy@1.0.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:miller-rabin@2.0.1": {
      "bn.js": "npm:bn.js@2.0.5",
      "brorand": "npm:brorand@1.0.5"
    },
    "npm:minimatch@2.0.8": {
      "brace-expansion": "npm:brace-expansion@1.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0"
    },
    "npm:once@1.3.2": {
      "wrappy": "npm:wrappy@1.0.1"
    },
    "npm:parse-asn1@3.0.1": {
      "asn1.js": "npm:asn1.js@2.0.4",
      "browserify-aes": "npm:browserify-aes@1.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:pbkdf2@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.3",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:public-encrypt@2.0.1": {
      "bn.js": "npm:bn.js@2.0.5",
      "browserify-rsa": "npm:browserify-rsa@2.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@3.0.1",
      "randombytes": "npm:randombytes@2.0.1"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:randombytes@2.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:readable-stream@1.1.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:reflect-metadata@0.1.0": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:rsvp@3.0.18": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:rtts_assert@2.0.0-alpha.26": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0"
    },
    "npm:rx@2.5.1": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:semver@2.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:sha.js@2.4.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:source-map-support@0.2.10": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "querystring": "github:jspm/nodelibs-querystring@0.1.0",
      "source-map": "npm:source-map@0.1.32"
    },
    "npm:source-map@0.1.32": {
      "amdefine": "npm:amdefine@0.1.1",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.13"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:traceur@0.0.87": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "commander": "npm:commander@2.6.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "glob": "npm:glob@4.3.5",
      "module": "github:jspm/nodelibs-module@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1",
      "rsvp": "npm:rsvp@3.0.18",
      "semver": "npm:semver@2.3.2",
      "source-map-support": "npm:source-map-support@0.2.10",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:zone.js@0.5.0": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    "npm:zone.js@0.5.1": {
      "process": "github:jspm/nodelibs-process@0.1.1"
    }
  }
});

